name: "nfl_dbt"
version: "1.0"

profile: "nfl"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

require-dbt-version: ">=1.2.0"

quoting:
    database: true
    identifier: false
    schema: false

vars:
    dbt_date:time_zone: "UTC"
    incremental_days: 30
    current_season: 2023
    years: 
        - 2016
        - 2017
        - 2018
        - 2019
        - 2020
        - 2021
        - 2022
        - 2023

models:
    nfl_dbt:
        staging:
            schema: staging
        analysis:
            schema: analysis
